apiVersion: v1
kind: ConfigMap
metadata:
  name: host-config
  namespace: {{ .Values.namespace }}
data:
  host.config.json: |
{{ .Values.hostconfig | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
  namespace: {{ .Values.namespace }}
data:
  site.config.json: |
{{ .Values.siteconfig | indent 4 }}

---

