---
- hosts: local
  become: yes
  strategy: free
  vars_files:
    - "{{inventory_dir}}/group_vars/all.yml"
    - "{{inventory_dir}}/common.yml"
  roles:

    - role: deploy-ui-spv-igot
      tags: [deploy-ui-spv-igot]
    - role: deploy-ui-proxies-service
      tags: [deploy-ui-proxies-service]
    - role: deploy-ui-static
      tags: [deploy-ui-static]

 
