---
- hosts: local
  become: yes
  strategy: free
  vars_files:
    - "{{inventory_dir}}/group_vars/all.yml"
    - "{{inventory_dir}}/common.yml"

  roles:
    - role: deploy-profanity-image-moderation-service
      tags: [deploy-profanity-image-moderation-service]
