---
- hosts: local
  become: yes
  strategy: free
  vars_files:
    - "{{inventory_dir}}/group_vars/all.yml"
    - "{{inventory_dir}}/common.yml"
    
  roles:
    - role: deploy-ui-mdo-igot
      tags: [deploy-ui-mdo-igot]
