---
- hosts: local
  become: yes
  strategy: free
  vars_files:
    - "{{inventory_dir}}/group_vars/all.yml"
    - "{{inventory_dir}}/common.yml"

  roles:
    - role: deploy-vega-console-service
      tags: [deploy-vega-console-service]
