apiVersion: v1
kind: ConfigMap
metadata:
  name: frac-dict-node-env-js
  namespace: {{ .Values.namespace }}
data:
  host.config.json: |
{{ .Values.hostconfig | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frac-dict-gatsby-env-js
  namespace: {{ .Values.namespace }}
data:
  site.config.json: |
{{ .Values.siteconfig | indent 4 }}

---
